# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 邱邱哥学习空间 
email: 873491063@qq.com
description: "可 爱 又 迷 人 反 派 角 色"
baseurl: "" # the subpath of your site, e.g. /blog
lang: "ch-CN"
locale: zh_CN # 本地化翻譯
url: "www.qiuqiuge.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  qiuqiuge
disqus_username:

# Build settings
markdown: kramdown
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"

# Theme settings
compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass
  style: compressed


images: '/assets/images'

# Site owner
owner:
  name: 阿邱
  email: 873491063@qq.com
  twitter: 我 没 有 推 特 哟
  google:
    ad-client:
    ad-slot:
  bio: "著 名 的 狠 人"
  avatar: bio-photo.jpg # 160x160 px image for author byline
  disqus-shortname:
